const myF = () => {
  try {
    console.log("this function called");
  } catch (e) {
    console.log("Something went wrong");
  }
};

myF();
